language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t maxefi/docker-kubernetes-aws -f Dockerfile.dev .  

script:
  - docker run -e CI=true maxefi/docker-kubernetes-aws npm run test